version: "3.6"

services:
    app:
        build:
            context: resources
            dockerfile: Dockerfile
        restart: 'unless-stopped'
        ports:
            - "8080:80"
        volumes:
            - ./code:/root:cached
    mariadb:
        image: mariadb:10.3
        restart: 'unless-stopped'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=ouvrages
        volumes:
            - ./resources:/docker-entrypoint-initdb.d:ro
    composer:
        build:
            context: resources
            dockerfile: composer.Dockerfile
        restart: 'no'
        command: composer install --prefer-source --no-plugins --optimize-autoloader --classmap-authoritative
        volumes:
          - ./code:/root:cached
          - ~/.composer:/root/.composer:ro
