version: "3.6"

services:
    app:
        build:
            context: resources
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./code:/root:cached
    mariadb:
        image: mariadb:10.3
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=ouvrages
        volumes:
            - ./resources:/docker-entrypoint-initdb.d:ro
